server {
    listen 8082;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /catalog/ {
        proxy_pass http://catalogapi:8080/;
    }

    location /booking/ {
        proxy_pass http://bookingapi:8081/;
    }
}
