server {
    listen 8082;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /catalog/ {
        proxy_pass https://catalogapi-mb007-gwddfnf2f6esa8gt.centralindia-01.azurewebsites.net/;
	proxy_set_header Host catalogapi-mb007-gwddfnf2f6esa8gt.centralindia-01.azurewebsites.net;
    }

    location /booking/ {
        proxy_pass https://bookingapi-mb007-gaa4bsekgweva8az.centralindia-01.azurewebsites.net/;
	proxy_set_header Host bookingapi-mb007-gaa4bsekgweva8az.centralindia-01.azurewebsites.net;
    }
}
